[package]

name        = "machine"
version     = "0.0.1"
authors     = ["Geoffroy Couprie <contact@geoffroycouprie.com>"]
description = "compiler checked state machine development"
license     = "MIT"
repository  = "https://github.com/Geal/machine"
readme      = "./README.md"
keywords    = ["state", "state-machine"]
