[package]

name        = "machine"
version     = "0.1.0"
authors     = ["Geoffroy Couprie <contact@geoffroycouprie.com>"]
description = "State machine utilities"
license     = "MIT/Apache-2.0"
repository  = "https://github.com/Geal/machine"
readme      = "./README.md"
keywords    = ["state", "state-machine"]

[features]
unstable = []
nightly = []
